<?php

namespace Tests\libraries;

/**
 * This class manages glider in the Dusk tet context.
 * 
 * A glider is an object to access glider data through a browser and a Dusk test context.
 * 
 * The persistence is managed by the WEB application and as we only have access to the WEB interface methods to retreive the information may be indirect.
 */

class GliderHandler {

    private $browser;
    private $tc;

    /** Constructor */
    function __construct($browser, $test_context) {
        $this->browser = $browser;
        $this->tc = $test_context;
    }

    public function gliderImage($glider) {
        $res = $glider['type'] . ' - ' . $glider['immat'];
        if (array_key_exists('numc', $glider)) {
            $res .= ' - (' . $glider['numc'] . ')';
        }
        return $res;
    }

    /** 
     * Check that a glider exists.
     * 
     * As glider IDs are not public (they are generated by the database), we check that the glider image is present in a select.
     */
    public function GliderExists($glider) {
        $selectValues = $this->tc->geyValuesFromSelect($this->browser, "vols_planeur/create", "vpmacid");

        $image = $this->gliderImage($glider);

        foreach ($selectValues as $key => $value) {
            if ($value == $image) {
                return true;
            }
        }
        return false;
    }

    public function FillFields($glider) {

        if (array_key_exists('construct', $glider)) {
            $this->browser->type('mpconstruc', $glider['construct']);
        }

        if (array_key_exists('type', $glider)) {
            $this->browser->type('mpmodele', $glider['type']);
        }

        if (array_key_exists('immat', $glider)) {
            $this->browser->type('mpimmat', $glider['immat']);
        }

        if (array_key_exists('numc', $glider)) {
            $this->browser->type('mpnumc', $glider['numc']);
        }

        if (array_key_exists('prix', $glider)) {
            $this->browser->select('mprix', $glider['prix']);
        }

        if (array_key_exists('prix_forfait', $glider)) {
            $this->browser->select('mprix_forfait', $glider['prix_forfait']);
        }

        if (array_key_exists('prix_moteur', $glider)) {
            $this->browser->select('mprix_moteur', $glider['prix_moteur']);
        }

        if (array_key_exists('nb_places', $glider)) {
            $this->browser->type('mpbiplace', $glider['nb_places']);
        }

        if (array_key_exists('type_proprio', $glider)) {
            switch ($glider['type_proprio']) {
                case 'Club':
                    $this->browser->radio('mpprive', "0");
                    break;
                case 'Privé':
                    $this->browser->radio('mpprive', "1");
                    break;
                case 'Extérieur':
                    $this->browser->radio('mpprive', "2");
                    break;
            }
        }

        if (array_key_exists('proprio', $glider)) {
            $this->browser->select('proprio', $glider['proprio']);
        }

        if (array_key_exists('banalise', $glider)) {
            if ($glider['banalise']) 
                $this->browser->check('banalise');
            else
                $this->browser->uncheck('banalise');
        }

        if (array_key_exists('autonome', $glider)) {
            if ($glider['autonome']) 
                $this->browser->check('mpautonome');
            else
                $this->browser->uncheck('mpautonome');
        }

        if (array_key_exists('treuillable', $glider)) {
            if ($glider['treuillable']) 
                $this->browser->check('mptreuil');
            else
                $this->browser->uncheck('mptreuil');
        }

        if (array_key_exists('active', $glider)) {
            if ($glider['active']) 
                $this->browser->check('actif');
            else
                $this->browser->uncheck('actif');
        }

    }

    /** 
     * Create gliders
     */
    public function CreateGliders($list = []) {
        foreach ($list as $elt) {
            if (!$this->GliderExists($elt)) {

                // Create product
                $this->tc->canAccess($this->browser, "planeur/create", ['Planeur']);

                $this->FillFields($elt);

                $this->browser->press('#validate');
            }
            $image = $this->gliderImage($elt);
            $this->tc->assertTrue(
                $this->GliderExists($elt),
                "glider exists: " . $image
            );
        }
    }

    /** 
     * Update glider
     */
    public function UpdateGlider($glider) {

        $id = $glider['immat'];
        $url = "planeur/edit/$id";
        $this->tc->canAccess($this->browser, $url);

        $this->FillFields($glider);

        $this->browser
            ->press('#validate')
            ->assertDontSee('404')
            ->assertDontSee('Le champ ');
    
    }

}
