<?php

namespace Tests\libraries;

/**
 * This class manages planes in the Dusk tet context.
 * 
 * A plane handler is an object to access plane data through a browser and a Dusk test context.
 * 
 * The persistence is managed by the WEB application and as we only have access to the WEB interface methods to retreive the information may be indirect.
 */

class PlaneFlightHandler {

    private $browser;
    private $tc;

    /** Constructor */
    function __construct($browser, $test_context) {
        $this->browser = $browser;
        $this->tc = $test_context;
    }

    /*
     * Extract the values of a select from an HTML page
     * returns an array of values => text
     * 
     * Special version for the plane flights
     */
    public function geyValuesFromSelect() {
        $this->tc->canAccess($this->browser, "event/create/asterix", []);

        $this->browser->screenshot('a_before_select');

        $this->browser->select('event_type_flight', "avion");

        $this->browser->screenshot('a_after_select');

        $id = "dropdown_avions";

        $js = "
        var result = [];
        var select = document.getElementById('" . $id . "');
        var options = select.options;
        for (var i = 0; i < options.length; i++) {
            text = options[i].text;
            value = options[i].value;
            result.push(value + ',' + text);
        }
        return result;";

        $sel = [];
        $results = $this->browser->script($js)[0];
        foreach ($results as $result) {
            $values = explode(',', $result);
            $sel[$values[0]] = $values[1];
        }
        return $sel;
    }

    /**
     * Check if a flight return by the REST API match a description in an array
     * $flight is the flight returned by the REST API
     * $plane_flight is an array with the description of the flight
     */
    public function match($flight, $plane_flight) {
        $dateFormat = "d/m/Y";
        $fdate = new \DateTime($flight->vadate);
        $date = $fdate->format($dateFormat);
        // echo $date . " " . $plane_flight['date'] . "\n";
        // var_dump($flight);
        if ($date != $plane_flight['date']) {
            echo "date $date does not match ". $plane_flight['date'] . "\n";
            return false;
        }
        if ($flight->vamacid != $plane_flight['plane']) {
            echo "plane does not match\n";
            return false;
        }
        if ($flight->vapilid != $plane_flight['pilot']) {
            echo "pilot does not match\n";
            return false;
        }
        if ($flight->vacdeb != $plane_flight['start_meter']) {
            echo "start meter " . $flight->vacdeb . " does not match " .  $plane_flight['start_meter'] . "\n";
            return false;
        }
        return true;
    }   


    /** 
     * Check that a plane exists.
     * 
     * As plane IDs are not public (they are generated by the database), we check that the plane image is present in a select
     * Maybe that I should rather rely on the test API ?
     */
    public function PlaneFlightExists($plane_flight) {

        $flights = $this->allFlights();
        foreach ($flights as $flight) {
            if ($this->match($flight, $plane_flight)) {
                return true;
            }
        }
        return false;
    }

    /** 
     * Create planes
     */
    public function CreatePlaneFlights($list = []) {
        foreach ($list as $flight) {

            $flight_number = $total = $this->tc->TableTotal($this->browser, "vols_avion/page");

            $this->tc->canAccess($this->browser, $flight['url']);

            $this->browser
                ->type('vadate', $flight['date'])
                ->select('vapilid', $flight['pilot'])
                ->select('vamacid', $flight['plane'])
                ->type('vahdeb', $flight['start_time'])
                ->type('vahfin', $flight['end_time'])
                ->type('vacdeb', $flight['start_meter'])
                ->type('vacfin', $flight['end_meter']);

            $this->browser->screenshot('a_before_flight');

            $this->browser
                ->press('#validate')
                ->assertDontSee('404');

            $this->browser->screenshot('after_flight');

            $this->tc->assertTrue(
                $this->PlaneFlightExists($flight),
                "plane flight exists: " . $flight['plane']
            );

            $new_flight_number = $total = $this->tc->TableTotal($this->browser, "vols_avion/page");
            
            $this->tc->assertEquals($flight_number + 1, $new_flight_number, "Flight number = " . $new_flight_number);
        }
    }

    /**
     * Get the latest flight in the database
     */
    public function latestFlight() {

        $url = $this->tc->fullUrl('api/vols_avion/ajax_latest');
        $json = file_get_contents($url);
        $obj = json_decode($json);
        if ($obj) return $obj[0];
        return null;
    }

    /**
     * Return the flights at a given date
     */
    public function allFlights($date = "") {

        $url = $this->tc->fullUrl('api/vols_avion/get');

        $json = file_get_contents($url);
        $obj = json_decode($json);
        if ($obj) return $obj;
        return null;
    }
}
